name: CICD workflow

on: 
  push:
    branches:
        - main
        - dev

  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Install tools
              run: sudo apt-get install -y g++ cppcheck clang-tidy libgtest-dev

            - name: Stylecheck with cppcheck
              run: cppcheck --enable=style,warning,performance --error-exitcode=1 .

            - name: Stylecheck with clang
              run:  clang-tidy main.cpp -checks='bugprone-*,performance-*,readability-*,modernize-*' -warnings-as-errors='*' -- -std=c++17

            - name: Build
              run: g++ main.cpp module1.cpp -o program -Wall -pedantic

            - name: Integration test
              run: |
                OUTPUT=$(./program)
                printf 'Output: %s\n' "$OUTPUT"
                if [ "$OUTPUT" = "Moin" ]; then
                  echo "Test bestanden"
                else
                  echo "Test fehlgeschlagen: '$OUTPUT'"
                  exit 1
                fi

            - name: Run main
              run: ./program  